# Generated by Django 4.0 on 2021-12-24 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_conteudo_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 0, 38, 57, 283857)),
        ),
    ]
